_BASE_: ../maskformer2_R50_bs16_50ep.yaml
MODEL:
  BACKBONE:
    NAME: "D2VitAdapterDinoV2"
  VIT_ADAPTER:
    NAME: 'vitb'
    VIT_WEIGHT: 'dinov2_vitb14_pretrain.pth'
    FREEZE_VIT: True
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  MASK_FORMER:
    NUM_OBJECT_QUERIES: 200
SOLVER:
  IMS_PER_BATCH: 8
  STEPS: (655556, 710184)
  MAX_ITER: 737500
